### PR TITLE
Fix sorting breaking task index behaviors

### LINKED ISSUE #184: Stop sorting for every command after sorting once
Causes indices to change when adding new tasks

### PR DESCRIPTION
**Pull request by initialshl**
Fixes #184.

### CODE REVIEW

File: src/main/java/teamfour/tasc/model/ModelManager.java [hunk 1]
```diff
@@ -429,9 +428,9 @@ public String toString() {
 
     //========== Inner classes/interfaces used for sorting ==================================================
 
-    private class EarliestFirstComparator implements Comparator<Task> {
+    private class EarliestFirstComparator implements Comparator<ReadOnlyTask> {
         @Override
-        public int compare(Task a, Task b) {
+        public int compare(ReadOnlyTask a, ReadOnlyTask b) {
```
Comment (yamgent) [inline src/main/java/teamfour/tasc/model/ModelManager.java:433]: I like the use of Interface Segregation Principle here.

**Review by yamgent — APPROVED** [review]
